#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S3,     Touch,          sensorHiTechnicTouchMux)
#pragma config(Sensor, S4,     sonar,          sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     RMotor,        tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     LMotor,        tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.


void initializeRobot()
{
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

  return;
}


task main()
{
motor(RMotor) = -80;
motor(LMotor) = -80;
wait10Msec(50);

servo(Claw) = -80;
wait10Msec(70);

motor(RMotor) = -80;
motor(LMotor) = 80;
wait10Msec(50);

motor(RMotor) = -80;
motor(LMotor) = -80;
wait10Msec (50);

servo(Claw)= 50;
wait10Msec(70);

motor(RMotor) = 50;
motor(LMotor) = 50;
wait10Msec(60);

motor(RMotor) = 50;
motor(LMotor) = -50;
wait10Msec(25);

motor(RMotor) = -80;
motor(LMotor) = -80;
wait10Msec (150);

motor(RMotor) = 80;
motor(LMotor) = -80;
wait10Msec (90);

motor(RMotor) = -77;
motor(LMotor) = -77;
wait10Msec (84);

motor(RMotor) = 0;
motor(LMotor) = 0;
wait10Msec (35);

motor(RMotor) = 80;
motor(LMotor) = -80;
wait10Msec (49);

motor(RMotor)= -80;
motor(LMotor)= -80;
wait10Msec (60);

motor(RMotor)= 0;
motor(LMotor)= 0;
wait10Msec (35);

motor(RMotor)= 80;
motor(LMotor)= 80;
wait10Msec (20);

motor(RMotor)= 80;
motor(LMotor)= -80;
wait10Msec (19);

motor(RMotor)= -80;
motor(LMotor)= 80;
wait10Msec (40);

motor(RMotor)= -80;
motor(LMotor)= -80;
wait10Msec (30);
}
